import json
import logging
from datetime import datetime, timedelta
from typing import Optional, List, Dict, Any

logger = logging.getLogger("JARVIS.MemoryLifecycleMixin")

class MemoryLifecycleMixin:
    # ── Workflow stats ────────────────────────────────────────────────── #

    def update_workflow_stats(
        self,
        goal_pattern: str,
        success: bool,
        exec_time_ms: int = 0,
        error: str = None,
    ) -> None:
        """Record outcome of a workflow execution for adaptive learning (non-blocking)."""
        import os
        if os.environ.get("JARVIS_E2E_SIM") == "1" or (goal_pattern and (goal_pattern.startswith("seed_") or goal_pattern.startswith("e2e_sim_"))):
            return
        self.enqueue_write(self._sync_update_workflow_stats, goal_pattern, success, exec_time_ms, error)

    def _sync_update_workflow_stats(
        self,
        goal_pattern: str,
        success: bool,
        exec_time_ms: int,
        error: str,
    ) -> None:
        ts = self._now()
        with self._lock.write_lock():
            existing = self.dbs["conversations"].execute(
                "SELECT id, success_count, fail_count, avg_exec_time_ms FROM workflow_stats WHERE goal_pattern = ?",
                (goal_pattern,),
            ).fetchone()

            if existing:
                row_id, succ, fail, avg_ms = existing
                new_succ = succ + (1 if success else 0)
                new_fail = fail + (0 if success else 1)
                total    = new_succ + new_fail
                new_avg  = int((avg_ms * (total - 1) + exec_time_ms) / total) if total else 0
                self.dbs["conversations"].execute(
                    """UPDATE workflow_stats
                       SET success_count=?, fail_count=?, avg_exec_time_ms=?, last_error=?, updated_at=?
                       WHERE id=?""",
                    (new_succ, new_fail, new_avg, error, ts, row_id),
                )
            else:
                self.dbs["conversations"].execute(
                    """INSERT INTO workflow_stats
                       (goal_pattern, success_count, fail_count, avg_exec_time_ms, last_error, updated_at)
                       VALUES (?, ?, ?, ?, ?, ?)""",
                    (
                        goal_pattern,
                        1 if success else 0,
                        0 if success else 1,
                        exec_time_ms,
                        error,
                        ts,
                    ),
                )
            self._commit()

    def get_workflow_stats(self, goal_pattern: str) -> Optional[Dict[str, Any]]:
        """Return success/fail stats for a given goal pattern."""
        with self._lock.read_lock():
            row = self.dbs["conversations"].execute(
                "SELECT success_count, fail_count, avg_exec_time_ms FROM workflow_stats WHERE goal_pattern = ?",
                (goal_pattern,),
            ).fetchone()
        if not row:
            return None
        succ, fail, avg = row
        total = succ + fail
        rate  = round(succ / total * 100, 1) if total else 0.0
        return {
            "success_count":   succ,
            "fail_count":      fail,
            "success_rate":    rate,
            "avg_exec_time_ms": avg,
        }

    # ── Agent reflections ─────────────────────────────────────────────── #

    def get_agent_reflections(self, days: int = 7, project: Optional[str] = None) -> List[Dict[str, Any]]:
        """Return recent reflections generated by the reflection engine, optionally filtered by project."""
        cutoff = (datetime.now() - timedelta(days=days)).isoformat()
        with self._lock.read_lock():
            if project and project != "general":
                rows = self.dbs["conversations"].execute(
                    """SELECT reflection, period, created_at FROM agent_reflections
                       WHERE created_at >= ? AND (project = ? OR project = 'general')
                       ORDER BY created_at DESC LIMIT 20""",
                    (cutoff, project),
                ).fetchall()
            else:
                rows = self.dbs["conversations"].execute(
                    """SELECT reflection, period, created_at FROM agent_reflections
                       WHERE created_at >= ? ORDER BY created_at DESC LIMIT 20""",
                    (cutoff,),
                ).fetchall()
        return [{"reflection": r[0], "period": r[1], "created_at": r[2]} for r in rows]

    # ── Persistent agent state ────────────────────────────────────────── #

    def persist_agent_state(
        self,
        goal: Optional[str],
        plan_dict: Optional[Dict],
        history: Optional[List],
        screen_ctx: Optional[Dict],
    ) -> None:
        """Checkpoint the current agent state to SQLite for crash recovery (non-blocking)."""
        self.enqueue_write(self._sync_persist_agent_state, goal, plan_dict, history, screen_ctx)

    def _sync_persist_agent_state(
        self,
        goal: Optional[str],
        plan_dict: Optional[Dict],
        history: Optional[List],
        screen_ctx: Optional[Dict],
    ) -> None:
        ts = self._now()
        with self._lock.write_lock():
            self.dbs["conversations"].execute(
                """INSERT OR REPLACE INTO agent_state
                   (id, current_goal, active_plan_json, execution_history_json, screen_context_json, updated_at)
                   VALUES (1, ?, ?, ?, ?, ?)""",
                (
                    goal,
                    json.dumps(plan_dict) if plan_dict else None,
                    json.dumps(history)   if history   else None,
                    json.dumps(screen_ctx) if screen_ctx else None,
                    ts,
                ),
            )
            self._commit(force=True)

    def restore_agent_state(self) -> Optional[Dict[str, Any]]:
        """Restore the last persisted agent state.  Returns None if none exists."""
        with self._lock.read_lock():
            row = self.dbs["conversations"].execute(
                """SELECT current_goal, active_plan_json, execution_history_json,
                          screen_context_json, updated_at
                   FROM agent_state WHERE id = 1"""
            ).fetchone()
        if not row:
            return None
        return {
            "current_goal":   row[0],
            "active_plan":    json.loads(row[1]) if row[1] else None,
            "history":        json.loads(row[2]) if row[2] else [],
            "screen_context": json.loads(row[3]) if row[3] else {},
            "saved_at":       row[4],
        }
